name = "Create Astral"
author = "Laskyyy"
version = "v2.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa27776647f87d58b8623903ec521550f0e54bf5eedf7fc1940519d15d8678b1"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
